name: antibiotic_red
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow
  - pip:
    - beautifulsoup4==4.10.0
    - bs4==0.0.1
    - humann==3.0.0
    - kneaddata==0.10.0
    - soupsieve==2.2.1
